name: Generate Release JSON
description: Validate run checks for the current version.

inputs:
  TOKEN:
    required: true
  BRANCH:
    required: true
  REPOSITORY:
    required: true
  MAINTAIN_USERNAME:
    required: true
  MAINTAIN_EMAIL:
    required: true
  TAG_NAME_FILTER:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout next release branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.BRANCH }}
    - shell: bash
      env:
        TOKEN: ${{ inputs.TOKEN }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        BRANCH: ${{ inputs.BRANCH }}
        MAINTAIN_USERNAME: ${{ inputs.MAINTAIN_USERNAME }}
        MAINTAIN_EMAIL: ${{ inputs.MAINTAIN_EMAIL }}
        TAG_NAME_FILTER: ${{ inputs.TAG_NAME_FILTER }}
      run: |
            npm install --no-package-lock --no-save @octokit/rest@19.0.3
            node .github/workflows/generate-release-json/generate-release-json.js
