name: Generate changelog

inputs:
  REPOSITORY:
    required: true
  HEAD_BRANCH_NAME:
    required: true
  BASE_TAG_NAME:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
            npm install --no-package-lock --no-save @octokit/core@3.4.0
            node ./.github/scripts/generate-changelog.js
      shell: bash
      env:
        TOKEN: ${{ env.GITHUB_TOKEN }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        HEAD_BRANCH_NAME: ${{ inputs.HEAD_BRANCH_NAME }}
        BASE_TAG_NAME: ${{ inputs.BASE_TAG_NAME }}
