name: Generate changelog

inputs:
  TOKEN:
    required: true
  REPOSITORY:
    required: true
  HEAD_BRANCH_NAME:
    required: true
  BASE_TAG_NAME:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
            npm install --no-package-lock --no-save semver@7.3.4 @octokit/core@3.4.0
            PREV_PACKAGE_VERSION=$(node -p "require('./package.json').last_cloud_version")
            node ./.github/scripts/generate-changelog.js
      shell: bash
      env:
        TOKEN: ${{ inputs.TOKEN }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        HEAD_BRANCH_NAME: ${{ inputs.HEAD_BRANCH_NAME }}
        BASE_TAG_NAME: ${{ inputs.BASE_TAG_NAME }}
