name: Bump version

inputs:
  CHANNEL:
    required: true
    
outputs:
  prev_version:
    value: ${{ steps.bump_version_step.outputs.prev_version }}

runs:
  using: "composite"
  steps:
    - run: |
            npm install --no-package-lock --no-save semver@7.3.4
            PREV_PACKAGE_VERSION=$(node -p "require('./package.json').version")
            NEW_PACKAGE_VERSION=$(node ./.github/scripts/update-prerelease-version.js ${{ inputs.CHANNEL }})
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            echo "PACKAGE_VERSION=${NEW_PACKAGE_VERSION}" >> $GITHUB_ENV
            run: echo "::set-output name=prev_version::$(echo $PREV_PACKAGE_VERSION)"
            echo "PACKAGE_VERSION : ${PACKAGE_VERSION}"
      shell: bash
      id: bump_version_step
