name: Push new version
description: Commit and push the new version to the remote repository after the "Bump version" workflow has been completed.

inputs:
  MAINTAIN_USERNAME:
    required: true
  MAINTAIN_EMAIL:
    required: true
  PACKAGE_VERSION:
    required: true

runs:
  using: "composite"
  steps:
    - run: |
            git config user.name ${{ inputs.MAINTAIN_USERNAME }}
            git config user.email ${{ inputs.MAINTAIN_EMAIL }}
            echo "Commit and push bump version ${{ inputs.PACKAGE_VERSION }}"
            git commit -am "Bump ${{ inputs.PACKAGE_VERSION }}"
            git push
      shell: bash
      