name: Create Git Tag
description: Generate a new Git version and push it to the remote repository.

inputs:
  MAINTAIN_USERNAME:
    description: 'The username of the user that will create the tag.'
    required: true
  MAINTAIN_EMAIL:
    description: 'The email of the user that will create the tag.'
    required: true
  MESSAGE:
    description: 'The message of the tag.'
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git config user.name ${{ inputs.MAINTAIN_USERNAME }}
        git config user.email ${{ inputs.MAINTAIN_EMAIL }}
        echo "Create tag v${{ inputs.MESSAGE }}"
        git tag -f "${{ inputs.MESSAGE }}"
        git push origin "${{ inputs.MESSAGE }}" --force
